# isort
# repos:
#   - repo: https://github.com/asottile/seed-isort-config
#     rev: v2.2.0
#     hooks:
#       - id: seed-isort-config
#   - repo: https://github.com/PyCQA/isort
#     rev: 5.12.0
#     hooks:
#       - id: isort
# black
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      args: # arguments to configure black
        - --line-length=120
      language_version: python3
# flake8
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      args: # arguments to configure flake8
        # making isort line length compatible with black
        - "--max-line-length=120"
        - "--max-complexity=14"
        - "--ignore=F403,F405"
